# Generated by Django 4.1.1 on 2023-09-01 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeC', models.CharField(max_length=10, unique=True)),
                ('nomC', models.CharField(max_length=30, unique=True)),
                ('descriptC', models.CharField(max_length=80)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteurC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeP', models.CharField(max_length=10, unique=True)),
                ('nomP', models.CharField(max_length=30, unique=True)),
                ('descriptP', models.CharField(max_length=80)),
                ('disponibleP', models.BooleanField(default=True)),
                ('quantiteMinP', models.PositiveIntegerField()),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteurP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.categorie')),
            ],
        ),
    ]
