# Generated by Django 4.1.1 on 2023-09-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='disponibleC',
            field=models.BooleanField(default=True),
        ),
    ]
