# Generated by Django 4.1.1 on 2023-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_commande_lignecommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='codeC',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
