# Generated by Django 4.1.1 on 2023-09-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0006_livraison_lignelivraison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignelivraison',
            old_name='date_created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='lignelivraison',
            old_name='date_modified',
            new_name='date_modification',
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateM', models.DateField()),
                ('qte', models.IntegerField()),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='', max_length=8)),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteurM', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('llivraison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.lignelivraison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
        ),
    ]
