# Generated by Django 4.1.1 on 2023-09-03 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0007_rename_date_created_lignelivraison_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeV', models.CharField(max_length=100, unique=True)),
                ('dateV', models.DateField()),
                ('client', models.CharField(max_length=100, unique=True)),
                ('remise', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteurV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateD', models.DateField()),
                ('dateF', models.DateField()),
                ('vigeur', models.CharField(choices=[('ACTUELLE', 'ACTUELLE'), ('OBSOLETE', 'OBSOLETE')], default='ACTUELLE', max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteurT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('NON-VA', 'NON-VA'), ('VA', 'VA')], default='NON-VA', max_length=15)),
                ('qte', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteurL', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
                ('tarification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.tarification')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.vente')),
            ],
        ),
    ]
