# Generated by Django 4.1.1 on 2023-09-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_vente_tarification_lignevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarification',
            name='prix',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
