# Generated by Django 4.1.1 on 2023-09-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_tarification_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarification',
            name='dateF',
            field=models.DateField(blank=True, null=True),
        ),
    ]
