# Generated by Django 4.1.1 on 2023-09-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_lignevente_qtedispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='sortie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.lignevente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='remise',
            field=models.IntegerField(default=0),
        ),
    ]
