# Generated by Django 4.1.1 on 2023-09-09 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0013_mouvement_sortie_alter_vente_remise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeC', models.CharField(max_length=100, unique=True)),
                ('dateC', models.DateField()),
                ('qte', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('EN COURS', 'EN COURS'), ('TRAITEE', 'TRAITEE'), ('PDT RUPTURE STOCK', 'PDT RUPTURE STOCK')], default='EN COURS', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteurC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autheur_consul', to=settings.AUTH_USER_MODEL)),
                ('auteurT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autheur_admin', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
        ),
    ]
